controllers:
    resource:
        path: ../src/Infrastructure/Api/
        namespace: App\Infrastructure\Api
    type: attribute

api_add_task:
    path: /api/todos
    controller: App\Infrastructure\Api\AddTaskController
    methods: ['POST']

api_get_tasks:
    path: /api/todos
    controller: App\Infrastructure\Api\GetTaskController
    methods: ['GET']
